spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/itStep
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate.ddl-auto: update
    show-sql: false
logging:
  file.name: .demo.log
  level:
    root: INFO
